# Generated by Django 6.0.2 on 2026-02-13 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('legal_document_type', models.CharField(choices=[('deed', 'Electronic Deed (صك إلكتروني)'), ('registry', 'Real Estate Registry (سجل عقاري)')], default='deed', help_text='نوع الوثيقة القانونية: صك إلكتروني أو سجل عقاري', max_length=20)),
                ('legal_document_no', models.CharField(blank=True, help_text='رقم الصك/السجل (اختياري)', max_length=100, null=True)),
                ('legal_document_file', models.FileField(blank=True, help_text='رفع ملف الصك الإلكتروني أو السجل العقاري', null=True, upload_to='legal_docs/')),
                ('city', models.CharField(default='Riyadh', max_length=80)),
                ('district', models.CharField(max_length=80)),
                ('street', models.CharField(max_length=120)),
                ('area_sqm', models.FloatField(help_text='المساحة الإجمالية بالمتر المربع')),
                ('north_street_width', models.FloatField(blank=True, null=True)),
                ('south_street_width', models.FloatField(blank=True, null=True)),
                ('east_street_width', models.FloatField(blank=True, null=True)),
                ('west_street_width', models.FloatField(blank=True, null=True)),
                ('land_type', models.CharField(choices=[('residential', 'Residential (سكني)'), ('commercial', 'Commercial (تجاري)'), ('agricultural', 'Agricultural (زراعي)'), ('industrial', 'Industrial (صناعي)')], help_text='نوع الأرض', max_length=30)),
                ('has_adjacent_lands', models.BooleanField(default=False, help_text='هل يوجد أراضي مجاورة ملاصقة للأرض؟')),
                ('street_frontage_length_m', models.FloatField(blank=True, help_text='طول واجهة الأرض على الشارع (بالمتر)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
