# Generated by Django 6.0.2 on 2026-02-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area_sqm',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_adjacent_lands',
        ),
        migrations.RemoveField(
            model_name='property',
            name='legal_document_file',
        ),
        migrations.RemoveField(
            model_name='property',
            name='legal_document_no',
        ),
        migrations.RemoveField(
            model_name='property',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='property',
            name='street',
        ),
        migrations.RemoveField(
            model_name='property',
            name='street_frontage_length_m',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='has_neighboring_lands',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='street_front_length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='property',
            name='east_street_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_type',
            field=models.CharField(choices=[('agricultural', 'Agricultural (زراعي)'), ('residential', 'Residential (سكني)'), ('commercial', 'Commercial (تجاري)'), ('industrial', 'Industrial (صناعي)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='legal_document_type',
            field=models.CharField(choices=[('deed', 'Electronic Deed (صك إلكتروني)'), ('registry', 'Real Estate Registry (سجل عقاري)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='north_street_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='south_street_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='west_street_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
