# Generated by Django 6.0.2 on 2026-02-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_area_sqm_remove_property_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='legal_document_file',
            field=models.FileField(blank=True, null=True, upload_to='legal_docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='legal_document_no',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='neighboring_directions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='property',
            name='east_street_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_type',
            field=models.CharField(choices=[('residential', 'Residential (سكني)'), ('commercial', 'Commercial (تجاري)'), ('agricultural', 'Agricultural (زراعي)'), ('industrial', 'Industrial (صناعي)')], default='residential', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='legal_document_type',
            field=models.CharField(choices=[('electronic_deed', 'Electronic Deed (صك إلكتروني)'), ('real_estate_registry', 'Real Estate Registry (سجل عقاري)')], default='electronic_deed', max_length=40),
        ),
        migrations.AlterField(
            model_name='property',
            name='north_street_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='south_street_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_front_length_m',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='west_street_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
