# Generated by Django 6.0.2 on 2026-02-16 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuationoffer',
            old_name='offered_by',
            new_name='valuer',
        ),
        migrations.RenameField(
            model_name='valuationrequest',
            old_name='requested_by',
            new_name='customer',
        ),
        migrations.AlterUniqueTogether(
            name='valuationoffer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='valuationrequest',
            name='notes',
        ),
        migrations.AddField(
            model_name='valuationoffer',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valuationoffer',
            name='offered_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuationrequest',
            name='chosen_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_for_requests', to='valuations.valuationoffer'),
        ),
        migrations.AlterField(
            model_name='valuationoffer',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='valuationrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('selected', 'Selected'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='valuationoffer',
            constraint=models.UniqueConstraint(fields=('request', 'valuer'), name='uniq_offer_per_request_per_valuer'),
        ),
        migrations.RemoveField(
            model_name='valuationoffer',
            name='price_sar',
        ),
        migrations.RemoveField(
            model_name='valuationoffer',
            name='status',
        ),
    ]
